import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

// Static, dependency-free preview. All links are relative for GitHub Pages and later custom-domain hosting.
const company = 'Nebukad International UG (haftungsbeschränkt)';
const words = {
 de: {nav:['Unternehmen','Apps','Schutzrechte','Über uns','Kontakt'],legal:'Impressum',privacy:'Datenschutz',menu:'Menü',skip:'Zum Inhalt',back:'Zurück zum Unternehmen',preview:'Designvorschau · Store-Veröffentlichungen, Schutzrechtsdaten und rechtliche Angaben noch in Vorbereitung.',
  eyebrow:'Ideen. Marken. Perspektiven.',hero:'Aus Ideen werden<br>bleibende Werte.',lead:'Wir entwickeln Produkte, bauen eigene Marken auf und schaffen die Grundlage für ihre langfristige Entwicklung.',learn:'Unser Unternehmen kennenlernen',
  companyLabel:'01 / Das Unternehmen',companyTitle:'Unternehmerisch denken.<br>Mit Substanz entwickeln.',companyText:'Nebukad International verbindet Produktentwicklung und Handel mit dem Aufbau eigener Marken. Wir begleiten Ideen von der Konzeption bis zur Vermarktung und bündeln die zugehörigen Schutzrechte im Unternehmen.',
  brandLabel:'02 / Unsere Marken',brandTitle:'Entwickelt für das,<br>was draußen zählt.',brandText:'NEO TACKLE ist eine Marke von Nebukad International für durchdachtes Angel- und Outdoorzubehör. Im Mittelpunkt stehen funktionale Produkte und das Zusammenspiel vernetzter Systeme.',brandFoot:'Eine Marke von Nebukad International',
  foundersLabel:'03 / Die Unternehmer',foundersTitle:'Zwei Perspektiven. Ein gemeinsamer Anspruch.',benRole:'Produktentwicklung & Unternehmertum',ben:'Langjährige Erfahrung in der Geschäftsführung sowie der Entwicklung und Vermarktung von Angelzubehör. Sein Hintergrund in BWL und Wirtschaftsrecht und technische Grundlagen im Maschinenbau verbinden wirtschaftliches Denken mit einem praktischen Blick auf Produkte.',husniRole:'Recht & unternehmerische Perspektive',husni:'Rechtsanwalt mit eigener Kanzlei und Erfahrung in Großkanzleien. Er ergänzt das Unternehmen um juristische Expertise und die Perspektive aus seiner anwaltlichen und unternehmerischen Tätigkeit.',
  rightsLabel:'04 / Entwicklung & Schutzrechte',rightsTitle:'Ideen entwickeln. Eigenständigkeit bewahren.',rightsText:'Die Marken und weiteren Schutzrechte unserer Entwicklungen sind bei Nebukad International gebündelt. Sie bilden eine Grundlage für den langfristigen Aufbau unseres Produkt- und Markenportfolios.',rightsLink:'Zum Schutzrechtsportfolio',appsLink:'Unsere Apps entdecken',
  ipTitle:'Unser Schutzrechtsportfolio.',ipIntro:'Marken, Patente, Gebrauchsmuster und Designs von Nebukad International im Überblick.',cols:['Schutzrechtsart','Bezeichnung','Schutzgebiet','Registernummer','Status'],types:['Marken','Patente','Gebrauchsmuster','Designs'],tableNote:'Die Einträge werden vor der Veröffentlichung ergänzt.',
  appsTitle:'Unsere Apps.',appsIntro:'Nebukad International ist der Herausgeber unserer Legacy Apps für bestehende Futterboote und Bivvy Lights. Hier finden Sie Informationen zu den Apps, Support und Datenschutz.',coming:'Store-Veröffentlichung in Vorbereitung',support:'Support',appPrivacy:'Datenschutz zur App',boatIntro:'Die Begleit-App für Ihr Futterboot.',boatText:'Boat Legacy verbindet die Steuerung Ihres Boots mit einer Kartenansicht und der Verwaltung Ihrer Angelplätze.',boatDevices:'Vorgesehen für New Direction Bait Boat 1 und Bait Boat 2. Der Funktionsumfang richtet sich nach dem jeweiligen Boot.',lightIntro:'Ihr Bivvy Light direkt im Blick.',lightText:'Bivvy Light Legacy bündelt die Bedienung der Lampe in einer übersichtlichen App – mit Weißlicht, individueller Lichtfarbe und Helligkeitsregelung.',lightDevices:'Für unterstützte New Direction Bivvy Lights. Die genaue Modellkompatibilität wird zum Store-Start ergänzt.',
  supportIntro:'Hinweise zu Verbindung und Bedienung.',boatQ:'Das Boot wird unter Android nicht gefunden.',boatA:'Prüfen Sie, ob Bluetooth und die Standortfunktion im Android-Schnellmenü eingeschaltet sind. Eine erteilte Standortberechtigung allein schaltet die Standortfunktion nicht ein. Prüfen Sie außerdem die Berechtigung für Geräte in der Nähe.',connectQ:'Was sollte ich vor dem Verbinden prüfen?',connectA:'Schalten Sie das Gerät ein und aktivieren Sie Bluetooth am Smartphone. Prüfen Sie die angefragten Berechtigungen und ob eine andere App bereits mit dem Gerät verbunden ist.',more:'Weitere Fragen',moreText:'Die Kontaktinformationen für den App-Support werden zum Veröffentlichungsstart ergänzt.',
  pending:'Diese Seite wird vor dem öffentlichen Start vervollständigt.',contactText:'Die geschäftlichen Kontaktdaten von Nebukad International werden hier vor der Veröffentlichung ergänzt.',legalText:'Anschrift, Registerangaben und die weiteren Anbieterinformationen werden vor dem öffentlichen Start hinterlegt.',privacyText:'Die Datenschutzerklärung dieser Website wird vor dem öffentlichen Start auf die tatsächlich eingesetzten Dienste und Kontaktwege abgestimmt.',appPrivacyText:'Die app-spezifische Datenschutzerklärung wird nach Prüfung der endgültigen App-Version ergänzt. Diese Vorschauseite ist noch keine vollständige Datenschutzerklärung und noch nicht für die Store-Einreichung vorgesehen.'},
 en: {nav:['Company','Apps','IP portfolio','About us','Contact'],legal:'Legal notice',privacy:'Privacy',menu:'Menu',skip:'Skip to content',back:'Back to the company',preview:'Design preview · Store releases, IP records and legal information are being prepared.',
  eyebrow:'Ideas. Brands. Perspectives.',hero:'Turning ideas into<br>lasting value.',lead:'We develop products, build our own brands and lay the foundations for their long-term growth.',learn:'Discover our company',
  companyLabel:'01 / The company',companyTitle:'An entrepreneurial mindset.<br>Development with substance.',companyText:'Nebukad International combines product development and trade with the creation of its own brands. We take ideas from concept to market and hold the associated intellectual property within the company.',
  brandLabel:'02 / Our brands',brandTitle:'Developed for what<br>matters outdoors.',brandText:'NEO TACKLE is a Nebukad International brand for thoughtfully designed angling and outdoor equipment. Its focus is on functional products and the interaction of connected systems.',brandFoot:'A brand of Nebukad International',
  foundersLabel:'03 / The entrepreneurs',foundersTitle:'Two perspectives. One shared ambition.',benRole:'Product development & entrepreneurship',ben:'Extensive experience in business management and the development and marketing of angling equipment. His background in business administration and business law, alongside foundational studies in mechanical engineering, combines commercial thinking with a practical understanding of products.',husniRole:'Law & an entrepreneurial perspective',husni:'A lawyer with his own practice and experience in major law firms. He contributes legal expertise and the perspective gained through his legal and entrepreneurial work.',
  rightsLabel:'04 / Development & intellectual property',rightsTitle:'Developing ideas. Preserving independence.',rightsText:'The brands and other intellectual property associated with our developments are held by Nebukad International. They provide a foundation for the long-term growth of our product and brand portfolio.',rightsLink:'View our IP portfolio',appsLink:'Explore our apps',
  ipTitle:'Our intellectual property.',ipIntro:'An overview of the trade marks, patents, utility models and designs held by Nebukad International.',cols:['IP category','Title','Territory','Registration number','Status'],types:['Trade marks','Patents','Utility models','Designs'],tableNote:'Records will be added before publication.',
  appsTitle:'Our apps.',appsIntro:'Nebukad International is the publisher of our Legacy apps for existing bait boats and bivvy lights. Find app information, support and privacy information here.',coming:'Store release in preparation',support:'Support',appPrivacy:'App privacy',boatIntro:'The companion app for your bait boat.',boatText:'Boat Legacy combines boat controls with a map view and management of your fishing spots.',boatDevices:'Intended for New Direction Bait Boat 1 and Bait Boat 2. Available features depend on the boat model.',lightIntro:'Your bivvy light at your fingertips.',lightText:'Bivvy Light Legacy brings lamp controls together in one clear interface, including white light, custom colour and brightness adjustment.',lightDevices:'For supported New Direction Bivvy Lights. Exact model compatibility will be added at the store launch.',
  supportIntro:'Connection and operation guidance.',boatQ:'My boat is not found on Android.',boatA:'Check that Bluetooth and Location are switched on in the Android quick settings. Granting location permission alone does not turn Location on. Also check the Nearby devices permission.',connectQ:'What should I check before connecting?',connectA:'Turn on the device and enable Bluetooth on your phone. Check the requested permissions and whether another app is already connected to the device.',more:'Further questions',moreText:'App support contact information will be added at launch.',
  pending:'This page will be completed before the public launch.',contactText:'Nebukad International’s business contact information will be added here before publication.',legalText:'The address, company registration details and other provider information will be added before the public launch.',privacyText:'The website privacy notice will be matched to the services and contact channels actually used before the public launch.',appPrivacyText:'The app-specific privacy notice will be added after review of the final app version. This preview page is not yet a complete privacy notice and is not ready for store submission.'}
};
const routes = ['index','apps','schutzrechte','kontakt','impressum','datenschutz','boat-support','boat-datenschutz','light-support','light-datenschutz'];
function link(slug,lang){return `${slug}${lang==='en'?'.en':''}.html`;}
function anchor(slug,lang,label,attr=''){return `<a href="${link(slug,lang)}" ${attr}>${label}</a>`;}
function intro(label,title,desc){return `<section class="page-intro container"><p class="eyebrow">Nebukad International / ${label}</p><h1>${title}</h1><p class="lead">${desc}</p></section>`;}
function home(w,lang){return `<section class="hero container"><div><p class="eyebrow">${w.eyebrow}</p><h1>${w.hero}</h1><p class="lead">${w.lead}</p><a class="text-link" href="#unternehmen">${w.learn} <span aria-hidden="true">↓</span></a></div><img class="seal" src="assets/nebukad-logo.webp" width="1244" height="1265" alt="Nebukad International" fetchpriority="high"></section>
<section id="unternehmen" class="company container"><p class="eyebrow">${w.companyLabel}</p><div><h2>${w.companyTitle}</h2><p>${w.companyText}</p></div></section>
<section class="brand"><div class="container"><div><p class="eyebrow">${w.brandLabel}</p><h2 class="brand-name">NEO TACKLE</h2><p class="tagline">Thinking Systems.</p></div><div><h2>${w.brandTitle}</h2><p>${w.brandText}</p><p class="attribution">${w.brandFoot}</p></div></div></section>
<section id="gruender" class="founders container"><p class="eyebrow">${w.foundersLabel}</p><h2>${w.foundersTitle}</h2><div class="founder-grid"><article><h3>Benjamin Ferger</h3><p class="eyebrow">${w.benRole}</p><p>${w.ben}</p></article><article><h3>Husni Celik</h3><p class="eyebrow">${w.husniRole}</p><p>${w.husni}</p></article></div></section>
<section class="rights-intro container"><p class="eyebrow">${w.rightsLabel}</p><h2>${w.rightsTitle}</h2><p>${w.rightsText}</p>${anchor('schutzrechte',lang,w.rightsLink+' →','class="text-link"')}<div class="app-index"><h2>Boat Legacy & Bivvy Light Legacy</h2>${anchor('apps',lang,w.appsLink+' →','class="text-link"')}</div></section>`;}
function apps(w,lang){return intro('Apps',w.appsTitle,w.appsIntro)+`<div class="container page-content">${[['boat','Boat Legacy',w.boatIntro,w.boatText,w.boatDevices],['light','Bivvy Light Legacy',w.lightIntro,w.lightText,w.lightDevices]].map(([id,name,title,desc,devices],i)=>`<article class="app-row"><div><p class="app-kicker">0${i+1} / ${name}</p><h2>${title}</h2><p class="status">${w.coming}</p></div><div><p>${desc}</p><p class="details">${devices}</p><div class="app-links">${anchor(id+'-support',lang,w.support)}${anchor(id+'-datenschutz',lang,w.appPrivacy)}</div></div></article>`).join('')}</div>`;}
function rights(w){return intro(w.nav[2],w.ipTitle,w.ipIntro)+`<div class="container page-content"><div class="table-wrap" tabindex="0" role="region" aria-label="${w.nav[2]}"><table><caption>${w.tableNote}</caption><thead><tr>${w.cols.map(c=>`<th scope="col">${c}</th>`).join('')}</tr></thead><tbody>${w.types.map(t=>`<tr><td>${t}</td><td>—</td><td>—</td><td>—</td><td>—</td></tr>`).join('')}</tbody></table></div></div>`;}
function support(w,lang,boat){const name=boat?'Boat Legacy':'Bivvy Light Legacy';return intro('Apps / '+name,name+' — '+w.support,w.supportIntro)+`<section class="container page-content"><div class="prose">${boat?`<details open><summary>${w.boatQ}</summary><p>${w.boatA}</p></details>`:''}<details ${boat?'':'open'}><summary>${w.connectQ}</summary><p>${w.connectA}</p></details><h2>${w.more}</h2><p>${w.moreText}</p><div class="app-links">${anchor('kontakt',lang,w.nav[4])}${anchor('apps',lang,'Apps')}</div></div></section>`;}
function legalNotice(w,lang){const de=lang==='de';return intro(w.legal,w.legal,company)+`<section class="container page-content"><div class="prose"><p>Nebukad International UG (haftungsbeschränkt)<br>Buchenweg 3<br>35684 Dillenburg<br>${de?'Deutschland':'Germany'}</p><h2>${de?'Geschäftsführer':'Managing directors'}</h2><p>Diplom-Wirtschaftsjurist, Diplom-Kaufmann Benjamin Ferger<br>Rechtsanwalt Husni Celik</p><h2>${de?'Registerangaben':'Registration details'}</h2><p>${de?'Registergericht':'Register court'}: Amtsgericht Wetzlar<br>${de?'Handelsregister':'Commercial register'}: HRB 9671</p><h2>${de?'Umsatzsteuer-Identifikationsnummer':'VAT identification number'}</h2><p>DE462594673</p><h2>${de?'Kontakt':'Contact'}</h2><p class="notice">${de?'Die E-Mail-Adresse und die weiteren Kontaktdaten werden ergänzt.':'The email address and further contact details will be added.'}</p></div></section>`;}
function pending(w,lang,slug){if(slug==='impressum')return legalNotice(w,lang);let title,copy;const isApp=slug.endsWith('-datenschutz');if(isApp){title=(slug.startsWith('boat')?'Boat Legacy':'Bivvy Light Legacy')+' — '+w.privacy;copy=w.appPrivacyText;}else{title=slug==='kontakt'?w.nav[4]:w.privacy;copy=slug==='kontakt'?w.contactText:w.privacyText;}return intro(title,title,company)+`<section class="container page-content"><div class="prose"><p class="notice">${w.pending}</p><p>${copy}</p></div></section>`;}
function render(slug,lang){const w=words[lang];let body,title;if(slug==='index'){body=home(w,lang);title='Nebukad International';}else if(slug==='apps'){body=apps(w,lang);title='Apps';}else if(slug==='schutzrechte'){body=rights(w);title=w.nav[2];}else if(slug.endsWith('-support')){body=support(w,lang,slug.startsWith('boat'));title=w.support;}else{body=pending(w,lang,slug);title=slug==='kontakt'?w.nav[4]:slug==='impressum'?w.legal:w.privacy;}
 const nav=[['index',w.nav[0],'#unternehmen'],['apps',w.nav[1],''],['schutzrechte',w.nav[2],''],['index',w.nav[3],'#gruender'],['kontakt',w.nav[4],'']].map(([s,label,hash])=>`<a href="${link(s,lang)}${hash}" ${slug===s&&!hash?'aria-current="page"':''}>${label}</a>`).join('');
 return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#e9e5db"><meta name="description" content="${lang==='de'?'Nebukad International – Produktentwicklung, eigene Marken und Legacy Apps.':'Nebukad International – product development, independent brands and Legacy apps.'}"><title>${title}${slug==='index'?'':' · Nebukad International'}</title><link rel="icon" type="image/webp" href="assets/nebukad-logo.webp"><link rel="stylesheet" href="style.css?v=2"><script src="site.js" defer></script></head><body><a class="skip" href="#inhalt">${w.skip}</a><header class="site-header container"><a class="wordmark" href="${link('index',lang)}" aria-label="Nebukad International">NEBUKAD <span>/</span> INTERNATIONAL</a><nav id="navigation" class="nav" aria-label="${lang==='de'?'Hauptnavigation':'Main navigation'}">${nav}</nav><div class="language" aria-label="${lang==='de'?'Sprache':'Language'}">${anchor(slug,'de','DE',`lang="de" hreflang="de" ${lang==='de'?'aria-current="page"':''}`)}<span aria-hidden="true">/</span>${anchor(slug,'en','EN',`lang="en" hreflang="en" ${lang==='en'?'aria-current="page"':''}`)}</div><button class="menu-button" type="button" aria-controls="navigation" aria-expanded="false">${w.menu}</button></header><main id="inhalt">${body}${slug==='index'?'':`<div class="container">${anchor('index',lang,'← '+w.back,'class="return-link"')}</div>`}</main><footer class="site-footer container"><span>${company}</span><nav class="footer-links" aria-label="Footer">${anchor('kontakt',lang,w.nav[4])}${anchor('impressum',lang,w.legal)}${anchor('datenschutz',lang,w.privacy)}</nav></footer><p class="preview-note">${w.preview}</p></body></html>`;
}
for(const lang of ['de','en'])for(const slug of routes){const file=link(slug,lang);mkdirSync(dirname(file),{recursive:true});writeFileSync(file,render(slug,lang));}
console.log(`Built ${routes.length*2} static pages (DE/EN).`);
