import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

// Static, dependency-free preview. All links are relative for GitHub Pages and later custom-domain hosting.
const company = 'Nebukad International UG (haftungsbeschränkt)';
const words = {
 de: {nav:['Unternehmen','Apps','Schutzrechte','Über uns','Kontakt'],legal:'Impressum',privacy:'Datenschutz',menu:'Menü',skip:'Zum Inhalt',back:'Zurück zum Unternehmen',preview:'Designvorschau · Store-Veröffentlichungen, Schutzrechtsdaten und rechtliche Angaben noch in Vorbereitung.',
  eyebrow:'Ideen. Marken. Perspektiven.',hero:'Aus Ideen werden<br>bleibende Werte.',lead:'Wir entwickeln Produkte, bauen eigene Marken auf und schaffen die Grundlage für ihre langfristige Entwicklung.',learn:'Unser Unternehmen kennenlernen',
  companyLabel:'01 / Das Unternehmen',companyTitle:'Unternehmerisch denken.<br>Mit Substanz entwickeln.',companyText:'Nebukad International verbindet Produktentwicklung und Handel mit dem Aufbau eigener Marken. Wir begleiten Ideen von der Konzeption bis zur Vermarktung und bündeln die zugehörigen Schutzrechte im Unternehmen.',
  brandLabel:'02 / Unsere Marken',brandTitle:'Entwickelt für das,<br>was draußen zählt.',brandText:'NEO TACKLE ist eine Marke von Nebukad International für durchdachtes Angel- und Outdoorzubehör. Im Mittelpunkt stehen funktionale Produkte und das Zusammenspiel vernetzter Systeme.',brandFoot:'Eine Marke von Nebukad International',
  foundersLabel:'03 / Die Unternehmer',foundersTitle:'Zwei Perspektiven. Ein gemeinsamer Anspruch.',benRole:'Produktentwicklung & Unternehmertum',ben:'Langjährige Erfahrung in der Geschäftsführung sowie der Entwicklung und Vermarktung von Angelzubehör. Sein Hintergrund in BWL und Wirtschaftsrecht und technische Grundlagen im Maschinenbau verbinden wirtschaftliches Denken mit einem praktischen Blick auf Produkte.',husniRole:'Recht & unternehmerische Perspektive',husni:'Rechtsanwalt mit eigener Kanzlei und Erfahrung in Großkanzleien. Er ergänzt das Unternehmen um juristische Expertise und die Perspektive aus seiner anwaltlichen und unternehmerischen Tätigkeit.',
  rightsLabel:'04 / Entwicklung & Schutzrechte',rightsTitle:'Ideen entwickeln. Eigenständigkeit bewahren.',rightsText:'Die Marken und weiteren Schutzrechte unserer Entwicklungen sind bei Nebukad International gebündelt. Sie bilden eine Grundlage für den langfristigen Aufbau unseres Produkt- und Markenportfolios.',rightsLink:'Zum Schutzrechtsportfolio',appsLink:'Unsere Apps entdecken',
  ipTitle:'Unser Schutzrechtsportfolio.',ipIntro:'Marken, Patente, Gebrauchsmuster und Designs von Nebukad International im Überblick.',cols:['Schutzrechtsart','Bezeichnung','Schutzgebiet','Registernummer','Status'],types:['Marken','Patente','Gebrauchsmuster','Designs'],tableNote:'Die Einträge werden vor der Veröffentlichung ergänzt.',
  appsTitle:'Unsere Apps.',appsIntro:'Nebukad International ist der Herausgeber unserer Legacy Apps für bestehende Futterboote und Bivvy Lights. Hier finden Sie Informationen zu den Apps, Support und Datenschutz.',coming:'Store-Veröffentlichung in Vorbereitung',support:'Support',appPrivacy:'Datenschutz zur App',boatIntro:'Die Begleit-App für Ihr Futterboot.',boatText:'Boat Legacy verbindet die Steuerung Ihres Boots mit einer Kartenansicht und der Verwaltung Ihrer Angelplätze.',boatDevices:'Vorgesehen für New Direction Bait Boat 1 und Bait Boat 2. Der Funktionsumfang richtet sich nach dem jeweiligen Boot.',lightIntro:'Ihr Bivvy Light direkt im Blick.',lightText:'Bivvy Light Legacy bündelt die Bedienung der Lampe in einer übersichtlichen App – mit Weißlicht, individueller Lichtfarbe und Helligkeitsregelung.',lightDevices:'Für unterstützte New Direction Bivvy Lights. Die genaue Modellkompatibilität wird zum Store-Start ergänzt.',
  supportIntro:'Hinweise zu Verbindung und Bedienung.',boatQ:'Das Boot wird unter Android nicht gefunden.',boatA:'Prüfen Sie, ob Bluetooth und die Standortfunktion im Android-Schnellmenü eingeschaltet sind. Eine erteilte Standortberechtigung allein schaltet die Standortfunktion nicht ein. Prüfen Sie außerdem die Berechtigung für Geräte in der Nähe.',connectQ:'Was sollte ich vor dem Verbinden prüfen?',connectA:'Schalten Sie das Gerät ein und aktivieren Sie Bluetooth am Smartphone. Prüfen Sie die angefragten Berechtigungen und ob eine andere App bereits mit dem Gerät verbunden ist.',more:'Weitere Fragen',moreText:'App-Support: <a href="mailto:info@nebukad-international.com">info@nebukad-international.com</a>',
  pending:'Diese Seite wird vor dem öffentlichen Start vervollständigt.',contactText:'Die geschäftlichen Kontaktdaten von Nebukad International werden hier vor der Veröffentlichung ergänzt.',legalText:'Anschrift, Registerangaben und die weiteren Anbieterinformationen werden vor dem öffentlichen Start hinterlegt.',privacyText:'Die Datenschutzerklärung dieser Website wird vor dem öffentlichen Start auf die tatsächlich eingesetzten Dienste und Kontaktwege abgestimmt.',appPrivacyText:'Die app-spezifische Datenschutzerklärung wird nach Prüfung der endgültigen App-Version ergänzt. Diese Vorschauseite ist noch keine vollständige Datenschutzerklärung und noch nicht für die Store-Einreichung vorgesehen.'},
 en: {nav:['Company','Apps','IP portfolio','About us','Contact'],legal:'Legal notice',privacy:'Privacy',menu:'Menu',skip:'Skip to content',back:'Back to the company',preview:'Design preview · Store releases, IP records and legal information are being prepared.',
  eyebrow:'Ideas. Brands. Perspectives.',hero:'Turning ideas into<br>lasting value.',lead:'We develop products, build our own brands and lay the foundations for their long-term growth.',learn:'Discover our company',
  companyLabel:'01 / The company',companyTitle:'An entrepreneurial mindset.<br>Development with substance.',companyText:'Nebukad International combines product development and trade with the creation of its own brands. We take ideas from concept to market and hold the associated intellectual property within the company.',
  brandLabel:'02 / Our brands',brandTitle:'Developed for what<br>matters outdoors.',brandText:'NEO TACKLE is a Nebukad International brand for thoughtfully designed angling and outdoor equipment. Its focus is on functional products and the interaction of connected systems.',brandFoot:'A brand of Nebukad International',
  foundersLabel:'03 / The entrepreneurs',foundersTitle:'Two perspectives. One shared ambition.',benRole:'Product development & entrepreneurship',ben:'Extensive experience in business management and the development and marketing of angling equipment. His background in business administration and business law, alongside foundational studies in mechanical engineering, combines commercial thinking with a practical understanding of products.',husniRole:'Law & an entrepreneurial perspective',husni:'A lawyer with his own practice and experience in major law firms. He contributes legal expertise and the perspective gained through his legal and entrepreneurial work.',
  rightsLabel:'04 / Development & intellectual property',rightsTitle:'Developing ideas. Preserving independence.',rightsText:'The brands and other intellectual property associated with our developments are held by Nebukad International. They provide a foundation for the long-term growth of our product and brand portfolio.',rightsLink:'View our IP portfolio',appsLink:'Explore our apps',
  ipTitle:'Our intellectual property.',ipIntro:'An overview of the trade marks, patents, utility models and designs held by Nebukad International.',cols:['IP category','Title','Territory','Registration number','Status'],types:['Trade marks','Patents','Utility models','Designs'],tableNote:'Records will be added before publication.',
  appsTitle:'Our apps.',appsIntro:'Nebukad International is the publisher of our Legacy apps for existing bait boats and bivvy lights. Find app information, support and privacy information here.',coming:'Store release in preparation',support:'Support',appPrivacy:'App privacy',boatIntro:'The companion app for your bait boat.',boatText:'Boat Legacy combines boat controls with a map view and management of your fishing spots.',boatDevices:'Intended for New Direction Bait Boat 1 and Bait Boat 2. Available features depend on the boat model.',lightIntro:'Your bivvy light at your fingertips.',lightText:'Bivvy Light Legacy brings lamp controls together in one clear interface, including white light, custom colour and brightness adjustment.',lightDevices:'For supported New Direction Bivvy Lights. Exact model compatibility will be added at the store launch.',
  supportIntro:'Connection and operation guidance.',boatQ:'My boat is not found on Android.',boatA:'Check that Bluetooth and Location are switched on in the Android quick settings. Granting location permission alone does not turn Location on. Also check the Nearby devices permission.',connectQ:'What should I check before connecting?',connectA:'Turn on the device and enable Bluetooth on your phone. Check the requested permissions and whether another app is already connected to the device.',more:'Further questions',moreText:'App support: <a href="mailto:info@nebukad-international.com">info@nebukad-international.com</a>',
  pending:'This page will be completed before the public launch.',contactText:'Nebukad International’s business contact information will be added here before publication.',legalText:'The address, company registration details and other provider information will be added before the public launch.',privacyText:'The website privacy notice will be matched to the services and contact channels actually used before the public launch.',appPrivacyText:'The app-specific privacy notice will be added after review of the final app version. This preview page is not yet a complete privacy notice and is not ready for store submission.'}
};
const routes = ['index','apps','schutzrechte','kontakt','impressum','datenschutz','boat-support','boat-datenschutz','light-support','light-datenschutz'];
function link(slug,lang){return `${slug}${lang==='en'?'.en':''}.html`;}
function anchor(slug,lang,label,attr=''){return `<a href="${link(slug,lang)}" ${attr}>${label}</a>`;}
function intro(label,title,desc){return `<section class="page-intro container"><p class="eyebrow">Nebukad International / ${label}</p><h1>${title}</h1><p class="lead">${desc}</p></section>`;}
function home(w,lang){return `<section class="hero container"><div><p class="eyebrow">${w.eyebrow}</p><h1>${w.hero}</h1><p class="lead">${w.lead}</p><a class="text-link" href="#unternehmen">${w.learn} <span aria-hidden="true">↓</span></a></div><img class="seal" src="assets/nebukad-logo.svg" width="1244" height="1265" alt="Nebukad International" fetchpriority="high"></section>
<section id="unternehmen" class="company container"><p class="eyebrow">${w.companyLabel}</p><div><h2>${w.companyTitle}</h2><p>${w.companyText}</p></div></section>
<section class="brand"><div class="container"><div><p class="eyebrow">${w.brandLabel}</p><h2 class="brand-name brand-logo-heading"><img class="neo-logo" src="assets/neo-tackle-white.svg" width="1564" height="624" alt="NEO TACKLE"></h2><p class="tagline">Thinking Systems.</p></div><div><h2>${w.brandTitle}</h2><p>${w.brandText}</p><p class="attribution">${w.brandFoot}</p></div></div></section>
<section id="gruender" class="founders container"><p class="eyebrow">${w.foundersLabel}</p><h2>${w.foundersTitle}</h2><div class="founder-grid"><article><h3>Benjamin Ferger</h3><p class="eyebrow">${w.benRole}</p><p>${w.ben}</p></article><article><h3>Husni Celik</h3><p class="eyebrow">${w.husniRole}</p><p>${w.husni}</p></article></div></section>
<section class="rights-intro container"><p class="eyebrow">${w.rightsLabel}</p><h2>${w.rightsTitle}</h2><p>${w.rightsText}</p>${anchor('schutzrechte',lang,w.rightsLink+' →','class="text-link"')}<div class="app-index"><h2>Boat Legacy & Bivvy Light Legacy</h2>${anchor('apps',lang,w.appsLink+' →','class="text-link"')}</div></section>`;}
function apps(w,lang){return intro('Apps',w.appsTitle,w.appsIntro)+`<div class="container page-content">${[['boat','Boat Legacy',w.boatIntro,w.boatText,w.boatDevices],['light','Bivvy Light Legacy',w.lightIntro,w.lightText,w.lightDevices]].map(([id,name,title,desc,devices],i)=>`<article class="app-row"><div><p class="app-kicker">0${i+1} / ${name}</p><h2>${title}</h2><p class="status">${w.coming}</p></div><div><p>${desc}</p><p class="details">${devices}</p><div class="app-links">${anchor(id+'-support',lang,w.support)}${anchor(id+'-datenschutz',lang,w.appPrivacy)}</div></div></article>`).join('')}</div>`;}
function rights(w){return intro(w.nav[2],w.ipTitle,w.ipIntro)+`<div class="container page-content"><div class="table-wrap" tabindex="0" role="region" aria-label="${w.nav[2]}"><table><caption>${w.tableNote}</caption><thead><tr>${w.cols.map(c=>`<th scope="col">${c}</th>`).join('')}</tr></thead><tbody>${w.types.map(t=>`<tr><td>${t}</td><td>—</td><td>—</td><td>—</td><td>—</td></tr>`).join('')}</tbody></table></div></div>`;}
function support(w,lang,boat){const name=boat?'Boat Legacy':'Bivvy Light Legacy';return intro('Apps / '+name,name+' — '+w.support,w.supportIntro)+`<section class="container page-content"><div class="prose">${boat?`<details open><summary>${w.boatQ}</summary><p>${w.boatA}</p></details>`:''}<details ${boat?'':'open'}><summary>${w.connectQ}</summary><p>${w.connectA}</p></details><h2>${w.more}</h2><p>${w.moreText}</p><div class="app-links">${anchor('kontakt',lang,w.nav[4])}${anchor('apps',lang,'Apps')}</div></div></section>`;}
function legalNotice(w,lang){const de=lang==='de';return intro(w.legal,w.legal,company)+`<section class="container page-content"><div class="prose"><p>Nebukad International UG (haftungsbeschränkt)<br>Buchenweg 3<br>35684 Dillenburg<br>${de?'Deutschland':'Germany'}</p><h2>${de?'Geschäftsführer':'Managing directors'}</h2>${de?'<p>Diplom-Wirtschaftsjurist, Diplom-Kaufmann Benjamin Ferger<br>Rechtsanwalt Husni Celik</p>':'<p>Benjamin Ferger<br>Diplom-Kaufmann (German university diploma in Business Administration)<br>Diplom-Wirtschaftsjurist (German university diploma in Business Law)</p><p>Husni Celik<br>Lawyer</p>'}<h2>${de?'Registerangaben':'Registration details'}</h2><p>${de?'Registergericht':'Register court'}: Amtsgericht Wetzlar<br>${de?'Handelsregister':'Commercial register'}: HRB 9671</p><h2>${de?'Umsatzsteuer-Identifikationsnummer':'VAT identification number'}</h2><p>DE462594673</p><h2>${de?'Kontakt':'Contact'}</h2><p><a href="mailto:info@nebukad-international.com">info@nebukad-international.com</a></p></div></section>`;}

const privacySections = {
  "de": [
    [
      "Verantwortlicher",
      "Nebukad International UG (haftungsbeschränkt), Buchenweg 3, 35684 Dillenburg, Deutschland. Vertreten durch die Geschäftsführer Benjamin Ferger und Husni Celik. E-Mail: <a href=\"mailto:info@nebukad-international.com\">info@nebukad-international.com</a>."
    ],
    [
      "Bereitstellung der Website",
      "Für nebukad-international.com ist Hosting bei IONOS SE, Elgendorfer Str. 57, 56410 Montabaur, vorgesehen. Beim Aufruf werden technisch notwendige Verbindungsdaten einschließlich der IP-Adresse verarbeitet, um die angeforderten Seiten auszuliefern und den Betrieb abzusichern. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO; unser berechtigtes Interesse ist die sichere und zuverlässige Bereitstellung unserer Unternehmenswebsite."
    ],
    [
      "Kontakt per E-Mail und Formular",
      "Unser E-Mail-Postfach wird bei IONOS betrieben. Wenn Sie uns per E-Mail oder Kontaktformular schreiben, verarbeiten wir Ihre E-Mail-Adresse, Ihren angegebenen Namen sowie Nachrichteninhalt und bei E-Mails gegebenenfalls Anhänge zur Bearbeitung Ihres Anliegens. Bei Vertragsanfragen gilt Art. 6 Abs. 1 lit. b DSGVO, bei anderen Anfragen Art. 6 Abs. 1 lit. f DSGVO auf Grundlage unseres Interesses an der Bearbeitung der Korrespondenz. Das Formular sendet Ihre Nachricht an unser Postfach. Zur Begrenzung missbräuchlicher Anfragen werden ein aus Ihrer IP-Adresse abgeleiteter Hash und ein Zeitstempel auf dem Hostingserver gespeichert; Nachrichteninhalte werden nicht in dieser Sperrdatei gespeichert. Einträge werden für eine Stunde berücksichtigt und bei einer späteren Anfrage bereinigt. Rechtsgrundlage ist unser berechtigtes Interesse am Schutz des Formulars nach Art. 6 Abs. 1 lit. f DSGVO. Die Angaben sind freiwillig; ohne eine Rückkontaktmöglichkeit können wir nicht antworten."
    ],
    [
      "Empfänger und Aufbewahrung",
      "Zugriff erhalten die mit Ihrer Anfrage befassten Personen und die für Hosting und E-Mail eingesetzten Dienstleister. Nachrichten werden gelöscht, sobald ihre Bearbeitung abgeschlossen ist und keine gesetzlichen Aufbewahrungspflichten oder berechtigten Gründe, etwa die Durchsetzung oder Abwehr von Ansprüchen, entgegenstehen. Für den IONOS-Betrieb müssen die konkreten Protokolldaten, deren Löschfristen sowie gegebenenfalls beteiligte Unterauftragnehmer und Drittlandübermittlungen noch mit dem gebuchten Produkt abgeglichen werden. Die <a href=\"https://www.ionos.de/terms-gtc/avv/\">IONOS-Vereinbarung zur Auftragsverarbeitung</a> bildet hierfür die vertragliche Grundlage; ihr konkreter Vertragsstatus ist vor dem Start zu prüfen."
    ],
    [
      "Cookies, Schriften und Analyse",
      "Der aktuelle Website-Code setzt keine Cookies und verwendet weder Local Storage noch Analyse- oder Werbetracking. Schriften und Bilder werden zusammen mit der Website ausgeliefert. Der Sprachwechsel erfolgt über separate Seiten. Im finalen Hosting zusätzlich aktivierte Statistikdienste sind vor dem Start gesondert zu prüfen."
    ],
    [
      "Ihre Rechte",
      "Unter den gesetzlichen Voraussetzungen haben Sie Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Datenübertragbarkeit. Soweit eine Verarbeitung auf einer Einwilligung beruht, können Sie diese mit Wirkung für die Zukunft widerrufen. Sie können sich bei einer Datenschutzaufsichtsbehörde beschweren, insbesondere beim Hessischen Beauftragten für Datenschutz und Informationsfreiheit."
    ],
    [
      "Widerspruchsrecht",
      "Sie können einer Verarbeitung auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO aus Gründen widersprechen, die sich aus Ihrer besonderen Situation ergeben. Wir verarbeiten die Daten dann nicht weiter, sofern keine zwingenden schutzwürdigen Gründe überwiegen oder die Verarbeitung der Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen dient."
    ],
    [
      "Apps und aktuelle Vorschau",
      "Für Boat Legacy und Bivvy Light Legacy sind eigene Datenschutzerklärungen vorgesehen. Diese Website-Vorschau läuft derzeit auf GitHub Pages; GitHub speichert dabei IP-Adressen zu Sicherheitszwecken. Weitere Informationen: <a href=\"https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages\">GitHub Pages</a> und <a href=\"https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement\">GitHub-Datenschutzerklärung</a>. Der Hostingabschnitt oben beschreibt den geplanten IONOS-Betrieb."
    ]
  ],
  "en": [
    [
      "Controller",
      "Nebukad International UG (haftungsbeschränkt), Buchenweg 3, 35684 Dillenburg, Germany. Represented by managing directors Benjamin Ferger and Husni Celik. Email: <a href=\"mailto:info@nebukad-international.com\">info@nebukad-international.com</a>."
    ],
    [
      "Website delivery",
      "Hosting for nebukad-international.com is planned with IONOS SE, Elgendorfer Str. 57, 56410 Montabaur, Germany. Technical connection data, including the IP address, is processed to deliver requested pages and protect operation. The legal basis is Article 6(1)(f) GDPR, reflecting our legitimate interest in providing a secure, reliable company website."
    ],
    [
      "Email and contact form enquiries",
      "Our email mailbox is hosted by IONOS. When you contact us by email or contact form, we process your email address, the name you provide, your message and any email attachments to handle your enquiry. Article 6(1)(b) GDPR applies to contractual enquiries; other correspondence is processed under Article 6(1)(f) GDPR based on our legitimate interest in handling enquiries. The form sends your message to our mailbox. To limit abuse, a hash derived from your IP address and a timestamp are kept on the hosting server; no message content is stored in this limit file. Entries are considered for one hour and removed on a subsequent submission. The basis is our legitimate interest in protecting the form under Article 6(1)(f) GDPR. Providing information is voluntary; we cannot reply without a return contact method."
    ],
    [
      "Recipients and retention",
      "Access is limited to people handling your enquiry and the service providers used for hosting and email. Messages are deleted when the enquiry has been resolved unless statutory retention duties or legitimate reasons, such as pursuing or defending claims, require further storage. The exact IONOS log data, retention periods, subprocessors and any international transfers must still be checked against the selected product. The <a href=\"https://www.ionos.de/terms-gtc/avv/\">IONOS data processing agreement</a> provides the contractual framework; its applicability to the account must be checked before launch."
    ],
    [
      "Cookies, fonts and analytics",
      "The current website code does not set cookies, use local storage or include analytics or advertising tracking. Fonts and images are served with the website. Language selection uses separate pages. Any additional statistics services enabled in the final hosting account must be reviewed before launch."
    ],
    [
      "Your rights",
      "Subject to the applicable legal conditions, you have rights of access, rectification, erasure, restriction and data portability. Where processing relies on consent, you may withdraw it for the future. You may complain to a data protection supervisory authority, including the Hessian Commissioner for Data Protection and Freedom of Information."
    ],
    [
      "Right to object",
      "You may object to processing based on Article 6(1)(f) GDPR on grounds relating to your particular situation. We will stop that processing unless overriding compelling legitimate grounds apply or the processing is required for establishing, exercising or defending legal claims."
    ],
    [
      "Apps and current preview",
      "Separate privacy notices are planned for Boat Legacy and Bivvy Light Legacy. This website preview currently uses GitHub Pages, which stores visitor IP addresses for security purposes. See <a href=\"https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages\">GitHub Pages</a> and the <a href=\"https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement\">GitHub privacy statement</a>. The hosting section above describes the planned IONOS deployment."
    ]
  ]
};
function websitePrivacy(w,lang){return intro(w.privacy,w.privacy,lang==='de'?'Entwurf für nebukad-international.com · Stand: 20. September 2026':'Draft for nebukad-international.com · Updated: 20 September 2026')+`<section class="container page-content"><div class="prose"><p class="notice">${lang==='de'?'Für den geplanten Betrieb bei IONOS vorbereitet. Die produktspezifischen Hostingangaben werden vor dem Start vervollständigt.':'Prepared for the planned IONOS deployment. Product-specific hosting details will be completed before launch.'}</p>${privacySections[lang].map(([title,body])=>`<h2>${title}</h2><p>${body}</p>`).join('')}</div></section>`;}
function contactPage(w,lang){return `<section class="page-intro container"><h1>${w.nav[4]}</h1></section><section class="container page-content"><div class="prose"><form id="contact-form" class="contact-form" action="contact.php" method="post"><label for="contact-name">${lang==='de'?'Name':'Name'}</label><input id="contact-name" name="name" autocomplete="name" required maxlength="100"><label for="contact-email">E-Mail</label><input id="contact-email" name="email" type="email" autocomplete="email" required maxlength="254"><label for="contact-message">${lang==='de'?'Nachricht':'Message'}</label><textarea id="contact-message" name="message" required maxlength="5000" rows="7"></textarea><div class="form-trap" aria-hidden="true"><label for="contact-website">Website</label><input id="contact-website" name="website" tabindex="-1" autocomplete="off"></div><p class="form-note">${lang==='de'?'Wir verwenden Ihre Angaben zur Bearbeitung Ihrer Anfrage.':'We use your details to handle your enquiry.'} ${anchor('datenschutz',lang,w.privacy)}</p><button type="submit" disabled>${lang==='de'?'Nachricht senden':'Send message'}</button><p id="form-status" role="status" aria-live="polite"></p><noscript><p>${lang==='de'?'Bitte aktivieren Sie JavaScript für das Formular oder schreiben Sie uns per E-Mail.':'Please enable JavaScript for the form or contact us by email.'}</p></noscript></form><script src="contact.js?v=2" defer></script></div></section>`;}

function pending(w,lang,slug){if(slug==='datenschutz')return websitePrivacy(w,lang);if(slug==='kontakt')return contactPage(w,lang);if(slug==='impressum')return legalNotice(w,lang);let title,copy;const isApp=slug.endsWith('-datenschutz');if(isApp){title=(slug.startsWith('boat')?'Boat Legacy':'Bivvy Light Legacy')+' — '+w.privacy;copy=w.appPrivacyText;}else{title=slug==='kontakt'?w.nav[4]:w.privacy;copy=slug==='kontakt'?w.contactText:w.privacyText;}return intro(title,title,company)+`<section class="container page-content"><div class="prose"><p class="notice">${w.pending}</p><p>${copy}</p></div></section>`;}
function render(slug,lang){const w=words[lang];let body,title;if(slug==='index'){body=home(w,lang);title='Nebukad International';}else if(slug==='apps'){body=apps(w,lang);title='Apps';}else if(slug==='schutzrechte'){body=rights(w);title=w.nav[2];}else if(slug.endsWith('-support')){body=support(w,lang,slug.startsWith('boat'));title=w.support;}else{body=pending(w,lang,slug);title=slug==='kontakt'?w.nav[4]:slug==='impressum'?w.legal:w.privacy;}
 const nav=[['index',w.nav[0],'#unternehmen'],['apps',w.nav[1],''],['schutzrechte',w.nav[2],''],['index',w.nav[3],'#gruender'],['kontakt',w.nav[4],'']].map(([s,label,hash])=>`<a href="${link(s,lang)}${hash}" ${slug===s&&!hash?'aria-current="page"':''}>${label}</a>`).join('');
 return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#e9e5db"><meta name="description" content="${lang==='de'?'Nebukad International – Produktentwicklung, eigene Marken und Legacy Apps.':'Nebukad International – product development, independent brands and Legacy apps.'}"><title>${title}${slug==='index'?'':' · Nebukad International'}</title><link rel="icon" type="image/svg+xml" href="assets/nebukad-logo.svg"><link rel="stylesheet" href="style.css?v=4"><script src="site.js" defer></script></head><body><a class="skip" href="#inhalt">${w.skip}</a><header class="site-header container"><a class="wordmark" href="${link('index',lang)}" aria-label="Nebukad International">NEBUKAD <span>/</span> INTERNATIONAL</a><nav id="navigation" class="nav" aria-label="${lang==='de'?'Hauptnavigation':'Main navigation'}">${nav}</nav><div class="language" aria-label="${lang==='de'?'Sprache':'Language'}">${anchor(slug,'de','DE',`lang="de" hreflang="de" ${lang==='de'?'aria-current="page"':''}`)}<span aria-hidden="true">/</span>${anchor(slug,'en','EN',`lang="en" hreflang="en" ${lang==='en'?'aria-current="page"':''}`)}</div><button class="menu-button" type="button" aria-controls="navigation" aria-expanded="false">${w.menu}</button></header><main id="inhalt">${body}${slug==='index'?'':`<div class="container">${anchor('index',lang,'← '+w.back,'class="return-link"')}</div>`}</main><footer class="site-footer container"><span>${company}</span><nav class="footer-links" aria-label="Footer">${anchor('kontakt',lang,w.nav[4])}${anchor('impressum',lang,w.legal)}${anchor('datenschutz',lang,w.privacy)}</nav></footer><p class="preview-note">${w.preview}</p></body></html>`;
}
for(const lang of ['de','en'])for(const slug of routes){const file=link(slug,lang);mkdirSync(dirname(file),{recursive:true});writeFileSync(file,render(slug,lang));}
console.log(`Built ${routes.length*2} static pages (DE/EN).`);
