import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

// Static, dependency-free preview. All links are relative for GitHub Pages and later custom-domain hosting.
const company = 'Nebukad International UG (haftungsbeschränkt)';
const words = {
 de: {nav:['Unternehmen','Apps','Schutzrechte','Über uns','Kontakt'],legal:'Impressum',privacy:'Datenschutz',menu:'Menü',skip:'Zum Inhalt',back:'Zurück zum Unternehmen',preview:'Designvorschau · Store-Veröffentlichungen, Schutzrechtsdaten und rechtliche Angaben noch in Vorbereitung.',
  eyebrow:'Ideen. Marken. Perspektiven.',hero:'Aus Ideen werden<br>bleibende Werte.',lead:'Wir entwickeln Produkte, bauen eigene Marken auf und schaffen die Grundlage für ihre langfristige Entwicklung.',learn:'Unser Unternehmen kennenlernen',
  companyLabel:'01 / Das Unternehmen',companyTitle:'Unternehmerisch denken.<br>Mit Substanz entwickeln.',companyText:'Nebukad International verbindet Produktentwicklung und Handel mit dem Aufbau eigener Marken. Wir begleiten Ideen von der Konzeption bis zur Vermarktung und bündeln die zugehörigen Schutzrechte im Unternehmen.',
  brandLabel:'02 / Unsere Marken',brandTitle:'Entwickelt für das,<br>was draußen zählt.',brandText:'NEO TACKLE ist eine Marke von Nebukad International für durchdachtes Angel- und Outdoorzubehör. Im Mittelpunkt stehen funktionale Produkte und das Zusammenspiel vernetzter Systeme.',brandFoot:'Eine Marke von Nebukad International',
  foundersLabel:'03 / Die Unternehmer',foundersTitle:'Zwei Perspektiven. Ein gemeinsamer Anspruch.',benRole:'Produktentwicklung & Unternehmertum',ben:'Langjährige Erfahrung in der Geschäftsführung sowie der Entwicklung und Vermarktung von Angelzubehör. Sein Hintergrund in BWL und Wirtschaftsrecht und technische Grundlagen im Maschinenbau verbinden wirtschaftliches Denken mit einem praktischen Blick auf Produkte.',husniRole:'Recht & unternehmerische Perspektive',husni:'Rechtsanwalt mit eigener Kanzlei und Erfahrung in Großkanzleien. Er ergänzt das Unternehmen um juristische Expertise und die Perspektive aus seiner anwaltlichen und unternehmerischen Tätigkeit.',
  rightsLabel:'04 / Entwicklung & Schutzrechte',rightsTitle:'Ideen entwickeln. Eigenständigkeit bewahren.',rightsText:'Die Marken und weiteren Schutzrechte unserer Entwicklungen sind bei Nebukad International gebündelt. Sie bilden eine Grundlage für den langfristigen Aufbau unseres Produkt- und Markenportfolios.',rightsLink:'Zum Schutzrechtsportfolio',appsLink:'Unsere Apps entdecken',
  ipTitle:'Unser Schutzrechtsportfolio.',ipIntro:'Marken, Patente, Gebrauchsmuster und Designs von Nebukad International im Überblick.',cols:['Schutzrechtsart','Bezeichnung','Schutzgebiet','Registernummer','Status'],types:['Marken','Patente','Gebrauchsmuster','Designs'],tableNote:'Die Einträge werden vor der Veröffentlichung ergänzt.',
  appsTitle:'Unsere Apps.',appsIntro:'Nebukad International ist der Herausgeber unserer Legacy Apps für bestehende Futterboote und Bivvy Lights. Hier finden Sie Informationen zu den Apps, Support und Datenschutz.',coming:'Store-Veröffentlichung in Vorbereitung',support:'Support',appPrivacy:'Datenschutz zur App',boatIntro:'Die Begleit-App für Ihr Futterboot.',boatText:'Boat Legacy verbindet die Steuerung Ihres Boots mit einer Kartenansicht und der Verwaltung Ihrer Angelplätze.',boatDevices:'Vorgesehen für New Direction Bait Boat 1 und Bait Boat 2. Der Funktionsumfang richtet sich nach dem jeweiligen Boot.',lightIntro:'Ihr Bivvy Light direkt im Blick.',lightText:'Bivvy Light Legacy bündelt die Bedienung der Lampe in einer übersichtlichen App – mit Weißlicht, individueller Lichtfarbe und Helligkeitsregelung.',lightDevices:'Für unterstützte New Direction Bivvy Lights. Die genaue Modellkompatibilität wird zum Store-Start ergänzt.',
  supportIntro:'Hinweise zu Verbindung und Bedienung.',boatQ:'Das Boot wird unter Android nicht gefunden.',boatA:'Prüfen Sie, ob Bluetooth und die Standortfunktion im Android-Schnellmenü eingeschaltet sind. Eine erteilte Standortberechtigung allein schaltet die Standortfunktion nicht ein. Prüfen Sie außerdem die Berechtigung für Geräte in der Nähe.',connectQ:'Was sollte ich vor dem Verbinden prüfen?',connectA:'Schalten Sie das Gerät ein und aktivieren Sie Bluetooth am Smartphone. Prüfen Sie die angefragten Berechtigungen und ob eine andere App bereits mit dem Gerät verbunden ist.',more:'Weitere Fragen',moreText:'App-Support: <a href="mailto:info@nebukad-international.com">info@nebukad-international.com</a>',
  pending:'Diese Seite wird vor dem öffentlichen Start vervollständigt.',contactText:'Die geschäftlichen Kontaktdaten von Nebukad International werden hier vor der Veröffentlichung ergänzt.',legalText:'Anschrift, Registerangaben und die weiteren Anbieterinformationen werden vor dem öffentlichen Start hinterlegt.',privacyText:'Die Datenschutzerklärung dieser Website wird vor dem öffentlichen Start auf die tatsächlich eingesetzten Dienste und Kontaktwege abgestimmt.',appPrivacyText:'Die app-spezifische Datenschutzerklärung wird nach Prüfung der endgültigen App-Version ergänzt. Diese Vorschauseite ist noch keine vollständige Datenschutzerklärung und noch nicht für die Store-Einreichung vorgesehen.'},
 en: {nav:['Company','Apps','IP portfolio','About us','Contact'],legal:'Legal notice',privacy:'Privacy',menu:'Menu',skip:'Skip to content',back:'Back to the company',preview:'Design preview · Store releases, IP records and legal information are being prepared.',
  eyebrow:'Ideas. Brands. Perspectives.',hero:'Turning ideas into<br>lasting value.',lead:'We develop products, build our own brands and lay the foundations for their long-term growth.',learn:'Discover our company',
  companyLabel:'01 / The company',companyTitle:'An entrepreneurial mindset.<br>Development with substance.',companyText:'Nebukad International combines product development and trade with the creation of its own brands. We take ideas from concept to market and hold the associated intellectual property within the company.',
  brandLabel:'02 / Our brands',brandTitle:'Developed for what<br>matters outdoors.',brandText:'NEO TACKLE is a Nebukad International brand for thoughtfully designed angling and outdoor equipment. Its focus is on functional products and the interaction of connected systems.',brandFoot:'A brand of Nebukad International',
  foundersLabel:'03 / The entrepreneurs',foundersTitle:'Two perspectives. One shared ambition.',benRole:'Product development & entrepreneurship',ben:'Extensive experience in business management and the development and marketing of angling equipment. His background in business administration and business law, alongside foundational studies in mechanical engineering, combines commercial thinking with a practical understanding of products.',husniRole:'Law & an entrepreneurial perspective',husni:'A lawyer with his own practice and experience in major law firms. He contributes legal expertise and the perspective gained through his legal and entrepreneurial work.',
  rightsLabel:'04 / Development & intellectual property',rightsTitle:'Developing ideas. Preserving independence.',rightsText:'The brands and other intellectual property associated with our developments are held by Nebukad International. They provide a foundation for the long-term growth of our product and brand portfolio.',rightsLink:'View our IP portfolio',appsLink:'Explore our apps',
  ipTitle:'Our intellectual property.',ipIntro:'An overview of the trade marks, patents, utility models and designs held by Nebukad International.',cols:['IP category','Title','Territory','Registration number','Status'],types:['Trade marks','Patents','Utility models','Designs'],tableNote:'Records will be added before publication.',
  appsTitle:'Our apps.',appsIntro:'Nebukad International is the publisher of our Legacy apps for existing bait boats and bivvy lights. Find app information, support and privacy information here.',coming:'Store release in preparation',support:'Support',appPrivacy:'App privacy',boatIntro:'The companion app for your bait boat.',boatText:'Boat Legacy combines boat controls with a map view and management of your fishing spots.',boatDevices:'Intended for New Direction Bait Boat 1 and Bait Boat 2. Available features depend on the boat model.',lightIntro:'Your bivvy light at your fingertips.',lightText:'Bivvy Light Legacy brings lamp controls together in one clear interface, including white light, custom colour and brightness adjustment.',lightDevices:'For supported New Direction Bivvy Lights. Exact model compatibility will be added at the store launch.',
  supportIntro:'Connection and operation guidance.',boatQ:'My boat is not found on Android.',boatA:'Check that Bluetooth and Location are switched on in the Android quick settings. Granting location permission alone does not turn Location on. Also check the Nearby devices permission.',connectQ:'What should I check before connecting?',connectA:'Turn on the device and enable Bluetooth on your phone. Check the requested permissions and whether another app is already connected to the device.',more:'Further questions',moreText:'App support: <a href="mailto:info@nebukad-international.com">info@nebukad-international.com</a>',
  pending:'This page will be completed before the public launch.',contactText:'Nebukad International’s business contact information will be added here before publication.',legalText:'The address, company registration details and other provider information will be added before the public launch.',privacyText:'The website privacy notice will be matched to the services and contact channels actually used before the public launch.',appPrivacyText:'The app-specific privacy notice will be added after review of the final app version. This preview page is not yet a complete privacy notice and is not ready for store submission.'}
};
const routes = ['index','apps','schutzrechte','kontakt','impressum','datenschutz','boat-support','boat-datenschutz','light-support','light-datenschutz'];
function link(slug,lang){return `${slug}${lang==='en'?'.en':''}.html`;}
function anchor(slug,lang,label,attr=''){return `<a href="${link(slug,lang)}" ${attr}>${label}</a>`;}
function intro(label,title,desc){return `<section class="page-intro container"><p class="eyebrow">Nebukad International / ${label}</p><h1>${title}</h1><p class="lead">${desc}</p></section>`;}
function home(w,lang){return `<section class="hero container"><div><p class="eyebrow">${w.eyebrow}</p><h1>${w.hero}</h1><p class="lead">${w.lead}</p><a class="text-link" href="#unternehmen">${w.learn} <span aria-hidden="true">↓</span></a></div><img class="seal" src="assets/nebukad-logo.svg" width="1244" height="1265" alt="Nebukad International" fetchpriority="high"></section>
<section id="unternehmen" class="company container"><p class="eyebrow">${w.companyLabel}</p><div><h2>${w.companyTitle}</h2><p>${w.companyText}</p></div></section>
<section class="brand"><div class="container"><div><p class="eyebrow">${w.brandLabel}</p><h2 class="brand-name brand-logo-heading"><img class="neo-logo" src="assets/neo-tackle-white.svg" width="1564" height="624" alt="NEO TACKLE"></h2><p class="tagline">Thinking Systems.</p></div><div><h2>${w.brandTitle}</h2><p>${w.brandText}</p><p class="attribution">${w.brandFoot}</p></div></div></section>
<section id="gruender" class="founders container"><p class="eyebrow">${w.foundersLabel}</p><h2>${w.foundersTitle}</h2><div class="founder-grid"><article><h3>Benjamin Ferger</h3><p class="eyebrow">${w.benRole}</p><p>${w.ben}</p></article><article><h3>Husni Celik</h3><p class="eyebrow">${w.husniRole}</p><p>${w.husni}</p></article></div></section>
<section class="rights-intro container"><p class="eyebrow">${w.rightsLabel}</p><h2>${w.rightsTitle}</h2><p>${w.rightsText}</p>${anchor('schutzrechte',lang,w.rightsLink+' →','class="text-link"')}<div class="app-index"><h2>Boat Legacy & Bivvy Light Legacy</h2>${anchor('apps',lang,w.appsLink+' →','class="text-link"')}</div></section>`;}
function apps(w,lang){return intro('Apps',w.appsTitle,w.appsIntro)+`<div class="container page-content">${[['boat','Boat Legacy',w.boatIntro,w.boatText,w.boatDevices],['light','Bivvy Light Legacy',w.lightIntro,w.lightText,w.lightDevices]].map(([id,name,title,desc,devices],i)=>`<article class="app-row"><div><p class="app-kicker">0${i+1} / ${name}</p><h2>${title}</h2><p class="status">${w.coming}</p></div><div><p>${desc}</p><p class="details">${devices}</p><div class="app-links">${anchor(id+'-support',lang,w.support)}${anchor(id+'-datenschutz',lang,w.appPrivacy)}</div></div></article>`).join('')}</div>`;}
function rights(w){return intro(w.nav[2],w.ipTitle,w.ipIntro)+`<div class="container page-content"><div class="table-wrap" tabindex="0" role="region" aria-label="${w.nav[2]}"><table><caption>${w.tableNote}</caption><thead><tr>${w.cols.map(c=>`<th scope="col">${c}</th>`).join('')}</tr></thead><tbody>${w.types.map(t=>`<tr><td>${t}</td><td>—</td><td>—</td><td>—</td><td>—</td></tr>`).join('')}</tbody></table></div></div>`;}
function support(w,lang,boat){const name=boat?'Boat Legacy':'Bivvy Light Legacy';return intro('Apps / '+name,name+' — '+w.support,w.supportIntro)+`<section class="container page-content"><div class="prose">${boat?`<details open><summary>${w.boatQ}</summary><p>${w.boatA}</p></details>`:''}<details ${boat?'':'open'}><summary>${w.connectQ}</summary><p>${w.connectA}</p></details><h2>${w.more}</h2><p>${w.moreText}</p><div class="app-links">${anchor('kontakt',lang,w.nav[4])}${anchor('apps',lang,'Apps')}</div></div></section>`;}
function legalNotice(w,lang){const de=lang==='de';return intro(w.legal,w.legal,company)+`<section class="container page-content"><div class="prose"><p>Nebukad International UG (haftungsbeschränkt)<br>Buchenweg 3<br>35684 Dillenburg<br>${de?'Deutschland':'Germany'}</p><h2>${de?'Geschäftsführer':'Managing directors'}</h2>${de?'<p>Diplom-Wirtschaftsjurist, Diplom-Kaufmann Benjamin Ferger<br>Rechtsanwalt Husni Celik</p>':'<p>Benjamin Ferger<br>Diplom-Kaufmann (German university diploma in Business Administration)<br>Diplom-Wirtschaftsjurist (German university diploma in Business Law)</p><p>Husni Celik<br>Lawyer</p>'}<h2>${de?'Registerangaben':'Registration details'}</h2><p>${de?'Registergericht':'Register court'}: Amtsgericht Wetzlar<br>${de?'Handelsregister':'Commercial register'}: HRB 9671</p><h2>${de?'Umsatzsteuer-Identifikationsnummer':'VAT identification number'}</h2><p>DE462594673</p><h2>${de?'Kontakt':'Contact'}</h2><p><a href="mailto:info@nebukad-international.com">info@nebukad-international.com</a></p></div></section>`;}

const privacySections = {
  "de": [
    [
      "Verantwortlicher",
      "Verantwortlich für die Verarbeitung personenbezogener Daten auf nebukad-international.com ist die Nebukad International UG (haftungsbeschränkt), Buchenweg 3, 35684 Dillenburg, Deutschland, vertreten durch die Geschäftsführer Benjamin Ferger und Husni Celik. Für Datenschutzanliegen erreichen Sie uns unter <a href=\"mailto:info@nebukad-international.com\">info@nebukad-international.com</a>."
    ],
    [
      "Hosting und technische Bereitstellung",
      "Die Website und unser E-Mail-Postfach werden bei IONOS SE, Elgendorfer Str. 57, 56410 Montabaur, Deutschland, betrieben. IONOS verarbeitet dabei die für die Bereitstellung von Website und E-Mail-Diensten erforderlichen Daten. Die Verwaltung der Website und des Postfachs sowie die Bearbeitung von Kontaktanfragen erfolgen durch die hierfür zuständigen Personen für Nebukad International."
    ],
    [
      "Aufruf der Website und Serverprotokolle",
      "Beim Aufruf verarbeitet der Server insbesondere Ihre IP-Adresse und technische Anfragedaten, um die Website auszuliefern und den Betrieb zu sichern. Die Hostingprotokolle umfassen die angeforderte Datei, Zugriffszeit, Herkunftsseite, Browser, Betriebssystem und Gerätetyp. Laut IONOS werden die Besucherdaten bei der Erhebung anonymisiert und acht Wochen gespeichert; die IP-Adresse wird in anonymisierter Form verarbeitet. Für diese Hosting-Besucherdaten nennt IONOS keine Übermittlung in Drittländer außerhalb der EU. Rechtsgrundlage für die personenbezogene Verarbeitung ist Art. 6 Abs. 1 lit. f DSGVO. Unser Interesse liegt in einem sicheren und zuverlässigen Betrieb. Einzelheiten: <a href=\"https://www.ionos.de/hilfe/datenschutz/datenverarbeitung-durch-ihr-ionos-produktes/datenverarbeitung-durch-webhosting-produkte/\">IONOS Webhosting</a>."
    ],
    [
      "Besucherstatistik mit IONOS WebAnalytics",
      "Zum Hosting gehört IONOS WebAnalytics zur statistischen Auswertung und technischen Verbesserung der Website. Laut IONOS verwendet der Dienst keine Cookies und anonymisiert die IP-Adresse unmittelbar nach der Übermittlung. Unsere Website bindet keinen zusätzlichen Analysepixel ein; die Hostingstatistik basiert auf den serverseitigen Zugriffsdaten. Soweit hierbei personenbezogene Daten verarbeitet werden, stützen wir dies auf Art. 6 Abs. 1 lit. f DSGVO und unser Interesse an der technischen Optimierung des Angebots. Weitere Informationen: <a href=\"https://www.ionos.de/hilfe/datenschutz/datenverarbeitung-durch-ihr-ionos-produktes/webanalytics/\">IONOS WebAnalytics</a>."
    ],
    [
      "Kontakt per E-Mail und Formular",
      "Bei einer Kontaktaufnahme verarbeiten wir Ihren Namen, Ihre E-Mail-Adresse, den Inhalt der Nachricht und bei E-Mails gegebenenfalls mitgesendete Anhänge sowie die zugehörigen Kommunikationsdaten. Dies dient der Bearbeitung und Beantwortung Ihres Anliegens. Betrifft die Anfrage einen Vertrag mit Ihnen oder vorvertragliche Maßnahmen auf Ihren Wunsch, gilt Art. 6 Abs. 1 lit. b DSGVO. Sonstige Anfragen, einschließlich der Kommunikation mit Ansprechpartnern von Unternehmen, bearbeiten wir auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO; unser Interesse ist die sachgerechte Bearbeitung der Korrespondenz. Das Kontaktformular übermittelt die Nachricht verschlüsselt über den IONOS-Mailserver an unser Postfach. Die Besucheradresse wird als Antwortadresse verwendet. Die Angaben werden den mit der Bearbeitung befassten Personen zugänglich gemacht. Die Kontaktaufnahme ist freiwillig. Im Formular sind Name, E-Mail-Adresse und Nachricht erforderlich; ohne diese Angaben ist ein Absenden nicht möglich. Alternativ können Sie uns per E-Mail kontaktieren."
    ],
    [
      "Schutz vor missbräuchlichen Anfragen",
      "Zur Begrenzung automatisierter oder übermäßig häufiger Formularanfragen verarbeiten wir einen aus der IP-Adresse abgeleiteten Hashwert und den Zeitpunkt des Versuchs. Diese Kennung ist pseudonymisiert, nicht anonym. Die separate Sperrdatei enthält keine Namen, E-Mail-Adressen oder Nachrichteninhalte. Einträge werden eine Stunde lang für die Begrenzung berücksichtigt und bei der nächsten Anfrage, die diese Prüfung erreicht, gelöscht; ohne weitere Anfrage können sie bis dahin gespeichert bleiben. Zusätzlich wird ein für reguläre Besucher nicht sichtbares Formularfeld zur Erkennung automatisierter Eingaben verwendet. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO; unser Interesse ist die Sicherung der Erreichbarkeit und der Schutz vor Spam."
    ],
    [
      "Aufbewahrung von Anfragen",
      "Wir speichern die Korrespondenz so lange, wie dies für die Bearbeitung des Anliegens erforderlich ist. Nach Abschluss löschen wir sie, sofern keine gesetzlichen Aufbewahrungspflichten oder Erfordernisse zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen entgegenstehen. Bei gesetzlichen Pflichten erfolgt die weitere Aufbewahrung nach Art. 6 Abs. 1 lit. c DSGVO für die jeweils geltende Frist; bei Rechtsansprüchen nach Art. 6 Abs. 1 lit. f DSGVO bis zum Wegfall des erforderlichen Sicherungszwecks."
    ],
    [
      "Cookies, lokale Inhalte und Verschlüsselung",
      "Die Website setzt keine eigenen Cookies und speichert keine Angaben im Local Storage oder Session Storage Ihres Browsers. Schriften und Bilder werden vom eigenen Webspace geladen. Der Sprachwechsel erfolgt über getrennte deutsche und englische Seiten. Google Analytics, Werbetracking, externe Schriftendienste, eingebettete Karten und Social-Media-Plugins werden nicht eingesetzt. Die Übertragung zwischen Browser und Website ist durch HTTPS verschlüsselt."
    ],
    [
      "Ihre Rechte",
      "Unter den gesetzlichen Voraussetzungen können Sie Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Datenübertragbarkeit verlangen (Art. 15–20 DSGVO). Soweit eine Verarbeitung auf einer Einwilligung beruht, können Sie diese jederzeit für die Zukunft widerrufen; die Rechtmäßigkeit der bisherigen Verarbeitung bleibt unberührt. Wenden Sie sich zur Ausübung Ihrer Rechte an die oben genannte Kontaktadresse. Sie haben zudem das Recht auf Beschwerde bei einer Datenschutzaufsichtsbehörde (Art. 77 DSGVO), insbesondere beim <a href=\"https://datenschutz.hessen.de/\">Hessischen Beauftragten für Datenschutz und Informationsfreiheit</a>."
    ],
    [
      "Widerspruchsrecht",
      "Sie können aus Gründen Ihrer besonderen Situation einer Verarbeitung widersprechen, die auf Art. 6 Abs. 1 lit. f DSGVO beruht. Wir beenden diese Verarbeitung, sofern wir keine überwiegenden zwingenden schutzwürdigen Gründe nachweisen können oder die Verarbeitung der Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen dient (Art. 21 DSGVO)."
    ],
    [
      "Automatisierte Entscheidungen und Geltungsbereich",
      "Wir treffen keine ausschließlich automatisierten Entscheidungen mit rechtlicher oder vergleichbar erheblicher Wirkung und betreiben kein entsprechendes Profiling. Diese Erklärung betrifft die Unternehmenswebsite. Die Datenverarbeitung der Apps Boat Legacy und Bivvy Light Legacy wird in gesonderten App-Datenschutzhinweisen beschrieben."
    ],
    [
      "Gesonderte GitHub-Vorschau",
      "Nur wenn Sie die gesonderte Vorschau unter neotheliberator.github.io/nebukad/ aufrufen, wird diese über GitHub Pages bereitgestellt. GitHub verarbeitet dabei unter anderem IP-Adressen zur Sicherheit. Der Formularversand ist dort deaktiviert. Informationen hierzu finden Sie in der <a href=\"https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement\">GitHub-Datenschutzerklärung</a>. Der Betrieb unter nebukad-international.com erfolgt bei IONOS."
    ]
  ],
  "en": [
    [
      "Controller",
      "The controller for personal data processed on nebukad-international.com is Nebukad International UG (haftungsbeschränkt), Buchenweg 3, 35684 Dillenburg, Germany, represented by managing directors Benjamin Ferger and Husni Celik. For privacy enquiries, contact <a href=\"mailto:info@nebukad-international.com\">info@nebukad-international.com</a>."
    ],
    [
      "Hosting and technical provision",
      "The website and our email mailbox are hosted by IONOS SE, Elgendorfer Str. 57, 56410 Montabaur, Germany. IONOS processes the data required to provide the website and email services. The website and mailbox are administered, and contact enquiries handled, by the people responsible for these tasks on behalf of Nebukad International."
    ],
    [
      "Website requests and server logs",
      "The server processes your IP address and technical request data to deliver the website and maintain security. Hosting logs include the requested file, time, referring page, browser, operating system and device type. IONOS states that visitor data is anonymised on collection and retained for eight weeks, with IP addresses processed in anonymised form. IONOS reports no transfers of these hosting visitor data to countries outside the EU. Personal data processing is based on Article 6(1)(f) GDPR and our interest in secure, reliable operation. Details: <a href=\"https://www.ionos.de/hilfe/datenschutz/datenverarbeitung-durch-ihr-ionos-produktes/datenverarbeitung-durch-webhosting-produkte/\">IONOS Webhosting</a>."
    ],
    [
      "IONOS WebAnalytics",
      "The hosting includes IONOS WebAnalytics for statistical evaluation and technical improvement. IONOS states that it uses no cookies and anonymises IP addresses immediately after transmission. Our website includes no additional analytics pixel; hosting statistics are based on server access data. To the extent personal data is processed, the basis is Article 6(1)(f) GDPR and our interest in technically improving the service. Details: <a href=\"https://www.ionos.de/hilfe/datenschutz/datenverarbeitung-durch-ihr-ionos-produktes/webanalytics/\">IONOS WebAnalytics</a>."
    ],
    [
      "Email and contact form",
      "When you contact us, we process your name, email address, message, any email attachments and associated communication data to handle and answer your enquiry. Article 6(1)(b) GDPR applies where the enquiry concerns a contract with you or pre-contractual steps at your request. Other enquiries, including correspondence with company representatives, are processed under Article 6(1)(f) GDPR based on our interest in handling correspondence appropriately. The form sends the message through an encrypted connection to the IONOS mail server for delivery to our mailbox. Your email address is used as the reply address. People responsible for handling the enquiry receive access. Contacting us is voluntary. The form requires a name, email address and message; submission is not possible without them. Alternatively, you may contact us by email."
    ],
    [
      "Protection against abusive submissions",
      "To limit automated or excessive submissions, we process a hash derived from the IP address and the time of the attempt. This identifier is pseudonymous, not anonymous. The separate rate-limit file contains no names, email addresses or message content. Entries count towards the limit for one hour and are removed on the next request reaching this check; if no further request occurs, they may remain stored until then. A form field hidden from ordinary visitors also helps identify automated input. The basis is Article 6(1)(f) GDPR and our interest in keeping the service available and preventing spam."
    ],
    [
      "Retention of correspondence",
      "We retain correspondence for as long as needed to handle the enquiry. We then delete it unless statutory retention duties or the establishment, exercise or defence of legal claims require further storage. Statutory retention is based on Article 6(1)(c) GDPR for the applicable period; retention for legal claims is based on Article 6(1)(f) GDPR until the relevant need ceases."
    ],
    [
      "Cookies, local resources and encryption",
      "The website sets no cookies of its own and stores no information in browser local storage or session storage. Fonts and images are served from our webspace. Language selection uses separate German and English pages. We use no Google Analytics, advertising tracking, external font services, embedded maps or social media plugins. Browser connections to the website are encrypted using HTTPS."
    ],
    [
      "Your rights",
      "Subject to the legal conditions, you may request access, rectification, erasure, restriction and data portability (Articles 15–20 GDPR). Where processing is based on consent, you may withdraw it at any time for the future without affecting the lawfulness of earlier processing. Please use the contact address above to exercise your rights. You may also complain to a data protection supervisory authority (Article 77 GDPR), including the <a href=\"https://datenschutz.hessen.de/\">Hessian Commissioner for Data Protection and Freedom of Information</a>."
    ],
    [
      "Right to object",
      "You may object on grounds relating to your particular situation to processing based on Article 6(1)(f) GDPR. We will stop unless we can demonstrate overriding compelling legitimate grounds or the processing serves the establishment, exercise or defence of legal claims (Article 21 GDPR)."
    ],
    [
      "Automated decisions and scope",
      "We do not make solely automated decisions with legal or similarly significant effects or conduct related profiling. This notice covers the company website. Processing by Boat Legacy and Bivvy Light Legacy is described in separate app privacy notices."
    ],
    [
      "Separate GitHub preview",
      "Only the separate preview at neotheliberator.github.io/nebukad/ is hosted on GitHub Pages. GitHub processes IP addresses, among other data, for security. Form submission is disabled on that preview. See the <a href=\"https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement\">GitHub privacy statement</a>. The website at nebukad-international.com is hosted by IONOS."
    ]
  ]
};
function websitePrivacy(w,lang){return intro(w.privacy,w.privacy,lang==='de'?'Datenschutzerklärung für nebukad-international.com · Stand: 20. September 2026':'Privacy notice for nebukad-international.com · Updated: 20 September 2026')+`<section class="container page-content"><div class="prose">${privacySections[lang].map(([title,body])=>`<h2>${title}</h2><p>${body}</p>`).join('')}</div></section>`;}
function contactPage(w,lang){return `<section class="page-intro container"><h1>${w.nav[4]}</h1></section><section class="container page-content"><div class="prose"><form id="contact-form" class="contact-form" action="contact.php" method="post"><label for="contact-name">${lang==='de'?'Name':'Name'}</label><input id="contact-name" name="name" autocomplete="name" required maxlength="100"><label for="contact-email">E-Mail</label><input id="contact-email" name="email" type="email" autocomplete="email" required maxlength="254"><label for="contact-message">${lang==='de'?'Nachricht':'Message'}</label><textarea id="contact-message" name="message" required maxlength="5000" rows="7"></textarea><div class="form-trap" aria-hidden="true"><label for="contact-website">Website</label><input id="contact-website" name="website" tabindex="-1" autocomplete="off"></div><p class="form-note">${lang==='de'?'Wir verwenden Ihre Angaben zur Bearbeitung Ihrer Anfrage.':'We use your details to handle your enquiry.'} ${anchor('datenschutz',lang,w.privacy)}</p><button type="submit" disabled>${lang==='de'?'Nachricht senden':'Send message'}</button><p id="form-status" role="status" aria-live="polite" aria-atomic="true"></p><noscript><p>${lang==='de'?'Bitte aktivieren Sie JavaScript für das Formular oder schreiben Sie uns per E-Mail.':'Please enable JavaScript for the form or contact us by email.'}</p></noscript></form><script src="contact.js?v=3" defer></script></div></section>`;}

function pending(w,lang,slug){if(slug==='datenschutz')return websitePrivacy(w,lang);if(slug==='kontakt')return contactPage(w,lang);if(slug==='impressum')return legalNotice(w,lang);let title,copy;const isApp=slug.endsWith('-datenschutz');if(isApp){title=(slug.startsWith('boat')?'Boat Legacy':'Bivvy Light Legacy')+' — '+w.privacy;copy=w.appPrivacyText;}else{title=slug==='kontakt'?w.nav[4]:w.privacy;copy=slug==='kontakt'?w.contactText:w.privacyText;}return intro(title,title,company)+`<section class="container page-content"><div class="prose"><p class="notice">${w.pending}</p><p>${copy}</p></div></section>`;}
function render(slug,lang){const w=words[lang];let body,title;if(slug==='index'){body=home(w,lang);title='Nebukad International';}else if(slug==='apps'){body=apps(w,lang);title='Apps';}else if(slug==='schutzrechte'){body=rights(w);title=w.nav[2];}else if(slug.endsWith('-support')){body=support(w,lang,slug.startsWith('boat'));title=w.support;}else{body=pending(w,lang,slug);title=slug==='kontakt'?w.nav[4]:slug==='impressum'?w.legal:w.privacy;}
 const nav=[['index',w.nav[0],'#unternehmen'],['apps',w.nav[1],''],['schutzrechte',w.nav[2],''],['index',w.nav[3],'#gruender'],['kontakt',w.nav[4],'']].map(([s,label,hash])=>`<a href="${link(s,lang)}${hash}" ${slug===s&&!hash?'aria-current="page"':''}>${label}</a>`).join('');
 return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#e9e5db"><meta name="description" content="${lang==='de'?'Nebukad International – Produktentwicklung, eigene Marken und Legacy Apps.':'Nebukad International – product development, independent brands and Legacy apps.'}"><title>${title}${slug==='index'?'':' · Nebukad International'}</title><link rel="icon" type="image/svg+xml" href="assets/nebukad-logo.svg"><link rel="stylesheet" href="style.css?v=${slug==='kontakt'?5:4}"><script src="site.js" defer></script></head><body><a class="skip" href="#inhalt">${w.skip}</a><header class="site-header container"><a class="wordmark" href="${link('index',lang)}" aria-label="Nebukad International">NEBUKAD <span>/</span> INTERNATIONAL</a><nav id="navigation" class="nav" aria-label="${lang==='de'?'Hauptnavigation':'Main navigation'}">${nav}</nav><div class="language" aria-label="${lang==='de'?'Sprache':'Language'}">${anchor(slug,'de','DE',`lang="de" hreflang="de" ${lang==='de'?'aria-current="page"':''}`)}<span aria-hidden="true">/</span>${anchor(slug,'en','EN',`lang="en" hreflang="en" ${lang==='en'?'aria-current="page"':''}`)}</div><button class="menu-button" type="button" aria-controls="navigation" aria-expanded="false">${w.menu}</button></header><main id="inhalt">${body}${slug==='index'?'':`<div class="container">${anchor('index',lang,'← '+w.back,'class="return-link"')}</div>`}</main><footer class="site-footer container"><span>${company}</span><nav class="footer-links" aria-label="Footer">${anchor('kontakt',lang,w.nav[4])}${anchor('impressum',lang,w.legal)}${anchor('datenschutz',lang,w.privacy)}</nav></footer>${slug==='datenschutz'?'':`<p class="preview-note">${w.preview}</p>`}</body></html>`;
}
for(const lang of ['de','en'])for(const slug of routes){const file=link(slug,lang);mkdirSync(dirname(file),{recursive:true});writeFileSync(file,render(slug,lang));}
console.log(`Built ${routes.length*2} static pages (DE/EN).`);
